defaults: &defaults
  working_directory: ~/samx
  docker:
    - image: circleci/node:8

whitelist: &whitelist
  paths:
    - .npmignore
    - coverage/*
    - dist/*
    - node_modules/*
    - lib/*
    - src/*
    - test/*
    - package.json
    - CHANGELOG.md

version: 2

jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/samx
          <<: *whitelist
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/samx
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/samx/.npmrc
      - run:
          name: Publish package
          command: npm publish --access=public

workflows:
  version: 2
  publish:
    jobs:
      - checkout
      - publish:
          requires:
            - checkout
          filters:
            branches:
              only: master